# Generated by Django 3.0.6 on 2020-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Danger',
            fields=[
                ('danger_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('danger_type', models.CharField(max_length=30)),
                ('danger_img', models.TextField()),
                ('danger_loc', models.TextField()),
            ],
            options={
                'db_table': 'danger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DongLevel',
            fields=[
                ('dong_level_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dong_level_tot', models.IntegerField()),
                ('dong_nm', models.CharField(max_length=30)),
                ('dong_loc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dong_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Female',
            fields=[
                ('female_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('female_crime_type', models.CharField(max_length=30)),
                ('female_crime_loc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'female',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('kid_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('kid_accident_type', models.CharField(max_length=30)),
                ('kid_accident_loc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyZone',
            fields=[
                ('safety_zone_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('safety_type', models.CharField(max_length=30)),
                ('safety_loc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'safety_zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('walker_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('walker_email', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'walker',
                'managed': False,
            },
        ),
    ]
