# Generated by Django 3.0.6 on 2020-05-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Walker',
        ),
    ]
