# Generated by Django 3.0.6 on 2020-07-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_map', '0002_delete_walker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Female2',
            fields=[
                ('female2_pk', models.AutoField(primary_key=True, serialize=False)),
                ('female2_crime_type', models.CharField(max_length=30)),
                ('female2_crime_loc', models.TextField()),
            ],
            options={
                'db_table': 'female2',
                'managed': False,
            },
        ),
    ]
