# Generated by Django 3.0.6 on 2020-10-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_map', '0003_female2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadtohexgrid',
            fields=[
                ('hexgrid_pk', models.AutoField(primary_key=True, serialize=False)),
                ('hex_q', models.IntegerField()),
                ('hex_r', models.IntegerField()),
                ('hexgrid_loc', models.TextField(blank=True, null=True)),
                ('hexgrid_gu', models.CharField(blank=True, max_length=30, null=True)),
                ('is_danger', models.IntegerField()),
            ],
            options={
                'db_table': 'roadToHexgrid',
                'managed': False,
            },
        ),
    ]
